fragment AllComponents on _IComponent {
    ...AllComponentsExceptGrid
    ...Grid # Grid needs to be separated from the rest of the components because of ContentArea and recursive rendering
    ...ContainerWidget # ContainerWidget also has a ContentArea, so it must be kept out of AllComponentsExceptGrid
}

fragment AllComponentsExceptGrid on _IComponent {
    ...Text
    ...Image
    ...CallToAction
    ...Video
    ...Paragraph
    ...Card
    ...Hero
    ...HeroCarousel
    ...Collapse
    ...ArticleList
    ...Button
    ...Iframe
    ...VideoExternal
    ...Divider
    ...OdpForm
    ...FacetedSearch
    ...DamAssetList
    ...JavascriptSnippet
}
